### ISSUE TITLE
训练过程中，PIX_AUPRO 为-100

### ISSUE THREAD

**Issue by iefengjian** [xcyao00/BGAD#14]
你好，我在mvtec数据集上训练，没有更改代码，训练结果的 PIX_AUPRO 都是-100正常吗

Epoch: 24        test_loss: 2.9807
IMG_AUROC:       last: 100.00    max: 100.00     epoch_max: 4
PIX_AUROC:       last: 99.64     max: 99.67      epoch_max: 21
PIX_AUPRO:       last: -100.00   max: -100.00    epoch_max: 0
Saving weights to output/bgad_fas_10/weights/mvtec_tf_efficientnet_b6_conditional_flow_model_hazelnut.pt

**Comment by xcyao00** [comment]
It's ok. As the pix_aupro calculation is time-consuming, I just set this to -1 when training. You can save the best checkpoint and calculate the pix_aupro for this checkpoint. Or you can change the code to calculate the pix_aupro every epoch.
