### ISSUE TITLE
Foreground Mask问题咨询

### ISSUE THREAD

**Issue by cqylunlun** [xcyao00/BGAD#8]
fg_mask前景覆盖的效果很好，但在项目中没有找到对应的算法。
请问能否开源文章中提及的grayscale binary thresholding algorithms，如果不方便可否提供实现思路或伪代码？

**Comment by xcyao00** [comment]
因为mvtec数据集中的前景和背景区分比较明显，我们就是简单使用了opencv中的分割函数。如果在你使用的数据集中，样本的前景背景不太容易区分，可能需要其他基于网络的分割方法。

**Comment by cqylunlun** [comment]
好的谢谢，大部分数据集前景背景区分明显，正在尝试引入人工先验生成前景掩码
